version: "3.7"
services:
  development:
    user: "${UID}:${GID}"
    working_dir: /home/dev
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECTS: /home/dev/projects
        GO_VERSION: 1.13.5
        RUBY_VERSION: 2.7.0
        USER_ID: "${UID}"
        GROUP_ID: "${GID}"
    volumes:
      - ./cache/projects:/home/dev/projects
      - ./cache/ssh:/home/dev/.ssh
      - ./cache/gnupg:/home/dev/.gnupg
      - ./cache/dotfiles:/home/dev/.dotfiles
      - ./cache/private:/home/dev/.private
