env:
  TERM: xterm-256color
  VIM_COLOR: hyper-light

window:
  startup_mode: Windowed
  dimensions:
    columns: 120
    lines: 40

  padding:
    x: 15
    y: 15

  dynamic_padding: true
  decorations: buttonless

scrolling:
  history: 1000
  multiplier: 3
  auto_scroll: false

tabspaces: 8

font:
  normal:
    family: Menlo
  size: 13.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: '0xffffff'
    foreground: '0x666666'

  # Normal colors
  normal:
    black:   '0x666666'
    red:     '0x666666'
    green:   '0xDDDDDD'
    yellow:  '0x666666'
    blue:    '0x666666'
    magenta: '0x666666'
    cyan:    '0x666666'
    white:   '0xFFFFFF'

  ## NOTE: I haven't modified these yet
  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0x666666'
    green:   '0x666666'
    yellow:  '0xffeb3b'
    blue:    '0x64b5f6'
    magenta: '0xba68c8'
    cyan:    '0x26c6da'
    white:   '0xe0e0e0'

  ## NOTE: I haven't modified these yet
  # Dim colors (Optional)
  dim:
    black:   '0x333333'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xdddddd'

  indexed_colors: []

visual_bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0

# Background opacity
background_opacity: 1.0

key_bindings:
  - { key: V, mods: Control|Shift,   action: Paste                  }
  - { key: C, mods: Control|Shift,   action: Copy                   }
  - { key: V, mods: Command,         action: Paste                  }
  - { key: C, mods: Command,         action: Copy                   }
  - { key: H, mods: Command,         action: Hide                   }
  - { key: Q, mods: Command,         action: Quit                   }
  - { key: K, mods: Command,         action: ClearHistory           }
  - { key: F, mods: Command|Control, action: ToggleSimpleFullscreen }
  - { key: L, mods: Control,         action: ClearLogNotice         }
  # disable all other keybindings
  - { key: Insert,   mods: Shift,               action: None }
  - { key: Key0,     mods: Control,             action: None }
  - { key: Equals,   mods: Control,             action: None }
  - { key: Add,      mods: Control,             action: None }
  - { key: Subtract, mods: Control,             action: None }
  - { key: Minus,    mods: Control,             action: None }
  - { key: Return,   mods: Alt,                 action: None }
  - { key: Key0,     mods: Command,             action: None }
  - { key: Equals,   mods: Command,             action: None }
  - { key: Add,      mods: Command,             action: None }
  - { key: Minus,    mods: Command,             action: None }
  - { key: K,        mods: Command,             action: None }
  - { key: M,        mods: Command,             action: None }
  - { key: W,        mods: Command,             action: None }
  - { key: Paste,                               action: None }
  - { key: Copy,                                action: None }
  - { key: L,        mods: Control,             action: None }
  - { key: PageUp,   mods: Shift,   mode: ~Alt, action: None }
  - { key: PageDown, mods: Shift,   mode: ~Alt, action: None }
  - { key: Home,     mods: Shift,   mode: ~Alt, action: None }
  - { key: End,      mods: Shift,   mode: ~Alt, action: None }


mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  # URL launcher
  # url:
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # When set to `None`, URL launching will be disabled completely.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    # launcher:
    #   program: xdg-open
    #   args: []

    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    # modifiers: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# dynamic_title: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
shell:
  program: /usr/local/bin/zsh
  # args:
  #   - --command=tmux

debug:
  # Should display the render timer
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: None

  # Print all received window events.
  print_events: false

  # Record all characters and escape sequences as test data.
  ref_test: false

# vim: nospell
